"""Added hashkey and name to Chat table

Revision ID: ee9381258dc6
Revises: fb80178221bc
Create Date: 2021-03-17 19:56:04.127716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9381258dc6'
down_revision = 'fb80178221bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('hash_key', sa.String(length=10), nullable=True))
    op.add_column('chat', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'username')
    op.drop_column('chat', 'hash_key')
    # ### end Alembic commands ###
